### ISSUE TITLE
Notifications revamp

### ISSUE THREAD

**Issue by ullebe1** [Bundedaterne/Bundr#1]
Instead of showing multiple identical notifications, notifications should either be merged with a text with the number of people waiting or be grouped together. However this would only be symptom treatment, ideally notifications should expire as soon as the person waiting has found a partner. This should limit number of notifications drastically, as there should be no more than one person waiting at any time.

**Comment by tyilo** [comment]
Unfortunately it is not possible to alter or withdraw a notifikation agter it is sent. This is a limit In the API we are using.
